### ISSUE TITLE
优化comment中的索引

### ISSUE THREAD

**Issue by wtune** [saysky/ForestBlog#37]
## 问题
表comment中缺少一些需要的索引，通过测试，我们发现加上这些索引可以极大地提高相关查询的性能(高达80%)，需要添加的索引分别如下所示：
### 1.comment.comment_article_id
[CommentMapper#listCommentByArticleId](https://github.com/saysky/ForestBlog/blob/ada9e4755a8210ba8e0929508b0a88282b44653d/ForestBlog/src/main/resources/mapper/CommentMapper.xml#L77)为根据文章来查找相关评论，这无疑评论相关的一个比较频繁的查询，为了提高该查询的效率，应该在article_id字段添加索引。
### 2.comment.comment_pid
[CommentMapper#listChildComment](https://github.com/saysky/ForestBlog/blob/ada9e4755a8210ba8e0929508b0a88282b44653d/ForestBlog/src/main/resources/mapper/CommentMapper.xml#L115)查询一条评论的子评论，同样也是一个比较常见的查询，因此值得在comment_pid字段添加索引从而加快该查询的速度。
## 解决方法
在下列字段添加索引
comment.comment_article_id
comment.comment_pid

**Comment by saysky** [comment]
谢谢你的建议，后期抽空统一改
