### ISSUE TITLE
修改部分表引擎提高全表行数统计的性能

### ISSUE THREAD

**Issue by wtune** [saysky/ForestBlog#39]
## 问题
在如下三个实现分页查询的过程中会产生统计全表行数的语句
### 1.[CommentServiceImpl#listCommentByPage](https://github.com/saysky/ForestBlog/blob/ada9e4755a8210ba8e0929508b0a88282b44653d/ForestBlog/src/main/java/com/liuyanzhao/ssm/blog/service/impl/CommentServiceImpl.java#L67)
SELECT count(0) FROM comment
### 2.[CategoryController#getArticleListByCategory](https://github.com/saysky/ForestBlog/blob/ada9e4755a8210ba8e0929508b0a88282b44653d/ForestBlog/src/main/java/com/liuyanzhao/ssm/blog/controller/home/CategoryController.java#L49)
SELECT COUNT(*) FROM         category
### 3.[TagController#getArticleListByTag](https://github.com/saysky/ForestBlog/blob/ada9e4755a8210ba8e0929508b0a88282b44653d/ForestBlog/src/main/java/com/liuyanzhao/ssm/blog/controller/home/TagController.java#L39)
SELECT COUNT(*) FROM  tag

在InnoDB中不会缓存表的元数据，因此执行这样的语句会造成比较大的时间开销，而MyISAM则缓存有表的元数据，统计行数可以在很短的时间内完成。**如果没有其它必须使用InnoDB的原因**，建议修改表的存储引擎从而优化这类语句。  
参考：https://dev.mysql.com/doc/refman/8.0/en/group-by-functions.html#function_count
## 解决方法
修改comment、category和tag表的存储引擎为MyISAM

**Comment by saysky** [comment]
谢谢你的建议，后期抽空统一改
