### ISSUE TITLE
为啥报404？

### ISSUE THREAD

**Issue by wzunique** [saysky/ForestBlog#5]
HTTP Status 404 - /ForestBlog/

type Status report

message /ForestBlog/

description The requested resource is not available.

Apache Tomcat/7.0.64

**Comment by saysky** [comment]
请将 ForestBlog 从地址栏拿掉。
首页是 http://localhost:8080 而非 http://localhost:8080/ForestBlog
具体怎么去掉，如果你使用 Eclipse，可以在 tomcat 里配置；如果你使用 IDEA，可以在配置里设置。
