### ISSUE TITLE
请问这款博客主题与知更鸟主题有啥关系?

### ISSUE THREAD

**Issue by Arisono** [saysky/ForestBlog#63]
请问下，你这个博客界面主题是不是照抄了  知更鸟的  主题？

**Comment by saysky** [comment]
前端HTML5界面是模仿他做的，项目架构是SSM的，不是PHP的。
照你这么说，如果京东界面跟天猫很像，京东跟天猫有什么区别。

**Comment by lvliang666666** [comment]
dasdsa
