### ISSUE TITLE
修复一个后台修改头像后不能显示的bug

### ISSUE THREAD

**Issue by GramYang** [saysky/ForestBlog#7]
感谢作者的无私奉献，这是一个非常好的学习ssm框架的项目。我也来班门弄斧一下：

在Admin/User/edit.jsp中第127行：

$("#userAvatar").attr("value", res.data.src);

下添加一行：

${userCustom.userAvatar} = res.data.src;

测试可行。

**Comment by saysky** [comment]
谢谢，这个项目很小，当初设计和做的时候很多不合理，也忽略了很多。
